export type SignLanguage = "ASL" | "TID";
export type SignCategory = "alphabet" | "number" | "common";

export interface SignItem {
  id: string;
  letter: string;
  name: string;
  language: SignLanguage;
  category: SignCategory;
  description: string;
  turkishDescription?: string;
  visualTip: string;
  handsRequired: 1 | 2;
  handShape: string;
  sampleKeywords: string[];
}

export const ASL_ALPHABET: SignItem[] = [
  {
    id: "asl_a",
    letter: "A",
    name: "Letter A",
    language: "ASL",
    category: "alphabet",
    description: "Make a fist with thumb resting alongside the curled index finger pointing up.",
    turkishDescription: "Dört parmak avuç içine yumulur, başparmak işaret parmağının yanına dik tutulur.",
    visualTip: "Thumb rests on the side of the curled index finger.",
    handsRequired: 1,
    handShape: "✊ (Thumb upright on side)",
    sampleKeywords: ["Apple", "Ask", "Always"],
  },
  {
    id: "asl_b",
    letter: "B",
    name: "Letter B",
    language: "ASL",
    category: "alphabet",
    description: "Hold 4 fingers straight up touching each other with thumb tucked across the palm.",
    turkishDescription: "Dört parmak bitişik ve dik yukarı bakar, başparmak avuç içine kıvrılır.",
    visualTip: "Four fingers up, flat palm facing forward.",
    handsRequired: 1,
    handShape: "✋ (Thumb tucked across palm)",
    sampleKeywords: ["Book", "Blue", "Baby"],
  },
  {
    id: "asl_c",
    letter: "C",
    name: "Letter C",
    language: "ASL",
    category: "alphabet",
    description: "Curved hand forming a 'C' shape with all fingers and thumb.",
    turkishDescription: "Elin tüm parmakları kavisli 'C' harfi şeklini alır.",
    visualTip: "Form a curved cup with fingers and thumb.",
    handsRequired: 1,
    handShape: "🤏 (Curved C shape)",
    sampleKeywords: ["Cat", "Car", "Coffee"],
  },
  {
    id: "asl_d",
    letter: "D",
    name: "Letter D",
    language: "ASL",
    category: "alphabet",
    description: "Index finger points straight up while other fingers touch thumb in an 'O' shape.",
    turkishDescription: "İşaret parmağı dik durur, diğer parmaklar başparmakla halka oluşturur.",
    visualTip: "Index straight up, thumb touching middle, ring, pinky.",
    handsRequired: 1,
    handShape: "☝️ (Thumb touching other 3 fingers)",
    sampleKeywords: ["Dog", "Day", "Door"],
  },
  {
    id: "asl_e",
    letter: "E",
    name: "Letter E",
    language: "ASL",
    category: "alphabet",
    description: "Curl all four fingertips down with thumb tucked underneath resting on the palm.",
    turkishDescription: "Dört parmağın ucu aşağı kıvrılır, başparmak alttan parmak uçlarına değer.",
    visualTip: "All fingertips curled resting on thumb.",
    handsRequired: 1,
    handShape: "✊ (Fingertips bent over thumb)",
    sampleKeywords: ["Eat", "Eye", "Easy"],
  },
  {
    id: "asl_f",
    letter: "F",
    name: "Letter F",
    language: "ASL",
    category: "alphabet",
    description: "Touch index and thumb together to make a circle; extend other three fingers upward.",
    turkishDescription: "İşaret ve başparmak birleşip halka yapar, diğer üç parmak açık yukarı bakar.",
    visualTip: "OK hand sign with 3 fingers spread up.",
    handsRequired: 1,
    handShape: "👌 (Three fingers spread up)",
    sampleKeywords: ["Fish", "Family", "Food"],
  },
  {
    id: "asl_g",
    letter: "G",
    name: "Letter G",
    language: "ASL",
    category: "alphabet",
    description: "Index and thumb point horizontally parallel to each other like holding a thick coin.",
    turkishDescription: "İşaret parmağı ve başparmak yatay öne uzatılır, diğerleri kapalıdır.",
    visualTip: "Index finger and thumb parallel pointing sideways.",
    handsRequired: 1,
    handShape: "👉 (Thumb parallel horizontally)",
    sampleKeywords: ["Good", "Girl", "Green"],
  },
  {
    id: "asl_h",
    letter: "H",
    name: "Letter H",
    language: "ASL",
    category: "alphabet",
    description: "Index and middle fingers extended together pointing horizontally; thumb tucked.",
    turkishDescription: "İşaret ve orta parmak bitişik yatay öne uzatılır.",
    visualTip: "Two fingers straight horizontal.",
    handsRequired: 1,
    handShape: "✌️ (Rotated horizontally)",
    sampleKeywords: ["Home", "Help", "Happy"],
  },
  {
    id: "asl_i",
    letter: "I",
    name: "Letter I",
    language: "ASL",
    category: "alphabet",
    description: "Extend pinky finger straight up; make a fist with remaining fingers with thumb over them.",
    turkishDescription: "Serçe parmak dik yukarı kalkar, diğer parmaklar yumruk şeklinde kapalıdır.",
    visualTip: "Pinky straight up, palm facing forward.",
    handsRequired: 1,
    handShape: "🤙 (Only pinky up)",
    sampleKeywords: ["Ice", "Idea", "Internet"],
  },
  {
    id: "asl_j",
    letter: "J",
    name: "Letter J",
    language: "ASL",
    category: "alphabet",
    description: "Start with 'I' pinky finger up, then draw a 'J' curve in the air with the pinky.",
    turkishDescription: "'I' pozisyonundaki serçe parmakla havada 'J' kavisli çizimi yapılır.",
    visualTip: "Pinky traces a hook motion.",
    handsRequired: 1,
    handShape: "🤙 (Pinky swoop motion)",
    sampleKeywords: ["Jump", "Joy", "Juice"],
  },
  {
    id: "asl_k",
    letter: "K",
    name: "Letter K",
    language: "ASL",
    category: "alphabet",
    description: "Index finger points up, middle finger angled forward, thumb tucked between them.",
    turkishDescription: "İşaret yukarı, orta parmak öne hafif eğik, başparmak aralarında durur.",
    visualTip: "V shape with thumb wedged between index and middle.",
    handsRequired: 1,
    handShape: "✌️ (Thumb between knuckles)",
    sampleKeywords: ["Key", "King", "Know"],
  },
  {
    id: "asl_l",
    letter: "L",
    name: "Letter L",
    language: "ASL",
    category: "alphabet",
    description: "Index finger points straight up, thumb extended perpendicular forming an 'L'.",
    turkishDescription: "İşaret parmağı dik, başparmak yatay açık 'L' harfi oluşturur.",
    visualTip: "Clear 90-degree 'L' shape.",
    handsRequired: 1,
    handShape: "👆 (L-shape with thumb)",
    sampleKeywords: ["Love", "Learn", "Light"],
  },
  {
    id: "asl_m",
    letter: "M",
    name: "Letter M",
    language: "ASL",
    category: "alphabet",
    description: "Thumb tucked under the first three curled fingers (index, middle, ring).",
    turkishDescription: "Başparmak ilk üç parmağın (işaret, orta, yüzük) altından dışarı uzanır.",
    visualTip: "Thumb peeking under 3 fingers.",
    handsRequired: 1,
    handShape: "✊ (Thumb under 3 fingers)",
    sampleKeywords: ["Mother", "Moon", "Music"],
  },
  {
    id: "asl_n",
    letter: "N",
    name: "Letter N",
    language: "ASL",
    category: "alphabet",
    description: "Thumb tucked under the first two curled fingers (index and middle).",
    turkishDescription: "Başparmak ilk iki parmağın (işaret ve orta) altından dışarı uzanır.",
    visualTip: "Thumb peeking under 2 fingers.",
    handsRequired: 1,
    handShape: "✊ (Thumb under 2 fingers)",
    sampleKeywords: ["Name", "Night", "New"],
  },
  {
    id: "asl_o",
    letter: "O",
    name: "Letter O",
    language: "ASL",
    category: "alphabet",
    description: "All fingertips touch the thumb to form a round 'O' shape.",
    turkishDescription: "Tüm parmak uçları başparmakla birleşip yuvarlak 'O' oluşturur.",
    visualTip: "Full circular O silhouette.",
    handsRequired: 1,
    handShape: "👌 (Round O circle)",
    sampleKeywords: ["Open", "Orange", "Ocean"],
  },
  {
    id: "asl_p",
    letter: "P",
    name: "Letter P",
    language: "ASL",
    category: "alphabet",
    description: "Like 'K' shape but rotated downward, index pointing horizontally and middle down.",
    turkishDescription: "'K' harfi pozisyonunun aşağı doğru eğilmiş halidir.",
    visualTip: "Downward pointing K shape.",
    handsRequired: 1,
    handShape: "👇 (K shape inverted down)",
    sampleKeywords: ["People", "Peace", "Place"],
  },
  {
    id: "asl_q",
    letter: "Q",
    name: "Letter Q",
    language: "ASL",
    category: "alphabet",
    description: "Like 'G' shape with index and thumb pointing downward.",
    turkishDescription: "'G' harfi pozisyonunun parmak uçları aşağı bakacak şekilde tutulmasıdır.",
    visualTip: "Downward pointing G shape.",
    handsRequired: 1,
    handShape: "👇 (G shape inverted down)",
    sampleKeywords: ["Quiet", "Quick", "Question"],
  },
  {
    id: "asl_r",
    letter: "R",
    name: "Letter R",
    language: "ASL",
    category: "alphabet",
    description: "Cross the middle finger over the index finger like making a good-luck wish.",
    turkishDescription: "Orta parmak işaret parmağının üzerine çapraz şekilde dolanır.",
    visualTip: "Crossed fingers (fingers crossed).",
    handsRequired: 1,
    handShape: "🤞 (Crossed fingers)",
    sampleKeywords: ["Red", "Rain", "Right"],
  },
  {
    id: "asl_s",
    letter: "S",
    name: "Letter S",
    language: "ASL",
    category: "alphabet",
    description: "Make a tight fist with thumb placed across the front of the curled fingers.",
    turkishDescription: "Sıkı yumruk yapılır, başparmak parmakların önünden enine sarar.",
    visualTip: "Thumb across the front of the fist knuckles.",
    handsRequired: 1,
    handShape: "✊ (Thumb across front)",
    sampleKeywords: ["Sun", "Star", "School"],
  },
  {
    id: "asl_t",
    letter: "T",
    name: "Letter T",
    language: "ASL",
    category: "alphabet",
    description: "Thumb tucked between the curled index and middle fingers.",
    turkishDescription: "Başparmak işaret ve orta parmak arasından dışarı çıkar.",
    visualTip: "Thumb between index and middle finger.",
    handsRequired: 1,
    handShape: "✊ (Thumb between 1st & 2nd finger)",
    sampleKeywords: ["Time", "Tree", "Today"],
  },
  {
    id: "asl_u",
    letter: "U",
    name: "Letter U",
    language: "ASL",
    category: "alphabet",
    description: "Index and middle fingers extended straight up together touching each other.",
    turkishDescription: "İşaret ve orta parmak bitişik şekilde dik yukarı bakar.",
    visualTip: "Two fingers together pointing straight up.",
    handsRequired: 1,
    handShape: "✌️ (Fingers closed tight together)",
    sampleKeywords: ["Up", "Use", "Under"],
  },
  {
    id: "asl_v",
    letter: "V",
    name: "Letter V",
    language: "ASL",
    category: "alphabet",
    description: "Index and middle fingers spread apart in a 'V' peace sign.",
    turkishDescription: "İşaret ve orta parmak açık 'V' (zafer) işareti şeklinde tutulur.",
    visualTip: "Classic V for Victory / Peace sign.",
    handsRequired: 1,
    handShape: "✌️ (Peace sign spread apart)",
    sampleKeywords: ["Victory", "Voice", "View"],
  },
  {
    id: "asl_w",
    letter: "W",
    name: "Letter W",
    language: "ASL",
    category: "alphabet",
    description: "Index, middle, and ring fingers spread upward forming a 'W'.",
    turkishDescription: "İşaret, orta ve yüzük parmakları açık şekilde yukarı bakar.",
    visualTip: "Three fingers spread up.",
    handsRequired: 1,
    handShape: "🖖 (3 fingers up forming W)",
    sampleKeywords: ["Water", "World", "Wind"],
  },
  {
    id: "asl_x",
    letter: "X",
    name: "Letter X",
    language: "ASL",
    category: "alphabet",
    description: "Index finger bent into a hook shape, other fingers curled into a fist.",
    turkishDescription: "İşaret parmağı kanca şeklinde kıvrılır, diğerleri yumruk halindedir.",
    visualTip: "Curved hook with index finger.",
    handsRequired: 1,
    handShape: "☝️ (Index hooked like pirate hook)",
    sampleKeywords: ["X-Ray", "Xylophone"],
  },
  {
    id: "asl_y",
    letter: "Y",
    name: "Letter Y",
    language: "ASL",
    category: "alphabet",
    description: "Thumb and pinky finger extended out while three middle fingers are curled in.",
    turkishDescription: "Başparmak ve serçe parmak açık, ortadaki 3 parmak kapalı (Alo işareti).",
    visualTip: "Hang loose / Shaka sign.",
    handsRequired: 1,
    handShape: "🤙 (Shaka thumb & pinky)",
    sampleKeywords: ["Yes", "Yellow", "You"],
  },
  {
    id: "asl_z",
    letter: "Z",
    name: "Letter Z",
    language: "ASL",
    category: "alphabet",
    description: "Index finger traces the shape of a 'Z' in the air.",
    turkishDescription: "İşaret parmağıyla havada 'Z' harfi çizilir.",
    visualTip: "Trace a Z path in the air with index.",
    handsRequired: 1,
    handShape: "👉 (Trace Z trajectory)",
    sampleKeywords: ["Zoo", "Zero", "Zone"],
  },
];

export const TID_ALPHABET: SignItem[] = [
  {
    id: "tid_a",
    letter: "A",
    name: "A Harfi",
    language: "TID",
    category: "alphabet",
    description: "İki elin baş ve işaret parmakları uç uca birleştirilerek üçgen (çatı) şekli oluşturulur.",
    visualTip: "İki elin parmaklarıyla tepe/çatı üçgeni yapılır.",
    handsRequired: 2,
    handShape: "🔺 (İki elle üçgen çatı)",
    sampleKeywords: ["Anne", "Arkadaş", "Araba"],
  },
  {
    id: "tid_b",
    letter: "B",
    name: "B Harfi",
    language: "TID",
    category: "alphabet",
    description: "İki elin baş ve işaret parmakları halka yapılarak üst üste 'B' gibi dokundurulur.",
    visualTip: "Sol ve sağ el halkaları üst üste 'B' formu verir.",
    handsRequired: 2,
    handShape: "👓 (İki el halkası birleşik)",
    sampleKeywords: ["Baba", "Bebek", "Başarı"],
  },
  {
    id: "tid_c",
    letter: "C",
    name: "C Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin parmakları kavisli şekilde 'C' harfi formunu alır.",
    visualTip: "Tek el kavisli C harfi.",
    handsRequired: 1,
    handShape: "🤏 (Kavisli C harfi)",
    sampleKeywords: ["Cami", "Cevap", "Cesur"],
  },
  {
    id: "tid_c_cedilla",
    letter: "Ç",
    name: "Ç Harfi",
    language: "TID",
    category: "alphabet",
    description: "'C' harfi formu yapıldıktan sonra el hafifçe aşağı doğru sallanır veya işaret parmağıyla altına nokta konur.",
    visualTip: "'C' yapılıp çengel/nokta hareketi verilir.",
    handsRequired: 1,
    handShape: "🤏 (C yapılıp aşağı silkelenir)",
    sampleKeywords: ["Çocuk", "Çay", "Çiçek"],
  },
  {
    id: "tid_d",
    letter: "D",
    name: "D Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sol işaret parmağı dik tutulur; sağ elin baş ve işaret parmağı 'C' yaparak sola yaslanır.",
    visualTip: "Sol dik çubuk, sağ kavis ile 'D' oluşturur.",
    handsRequired: 2,
    handShape: "I + C = D",
    sampleKeywords: ["Dede", "Dost", "Deniz"],
  },
  {
    id: "tid_e",
    letter: "E",
    name: "E Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sol el açık durur; sağ elin işaret, orta ve yüzük parmakları sol avuç içine 'E'nin 3 çizgisi gibi değer.",
    visualTip: "Sol avuç dikey, sağ 3 parmak yatay yaslanır.",
    handsRequired: 2,
    handShape: "✋ + 3 parmak",
    sampleKeywords: ["Evet", "Ev", "Elma"],
  },
  {
    id: "tid_f",
    letter: "F",
    name: "F Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sol işaret parmağı dik tutulur; sağ elin işaret ve orta parmağı sol parmağa yatay iki çizgi gibi değer.",
    visualTip: "Sol dik çubuk, sağ 2 parmak yatay çizgiler.",
    handsRequired: 2,
    handShape: "I + 2 yatay parmak",
    sampleKeywords: ["Fikir", "Fark", "Fener"],
  },
  {
    id: "tid_g",
    letter: "G",
    name: "G Harfi",
    language: "TID",
    category: "alphabet",
    description: "İki elin yumrukları başparmaklar birbirine bakacak şekilde yan yana getirilir.",
    visualTip: "İki yumruk başparmaklar yukarı bitişik.",
    handsRequired: 2,
    handShape: "🤜🤛 (Yumruklar yan yana)",
    sampleKeywords: ["Göz", "Güneş", "Güzel"],
  },
  {
    id: "tid_g_breve",
    letter: "Ğ",
    name: "Ğ Harfi",
    language: "TID",
    category: "alphabet",
    description: "'G' harfi yapıldıktan sonra eller hafifçe sağa sola sallanır.",
    visualTip: "'G' yumrukları hafifçe dalgalandırılır.",
    handsRequired: 2,
    handShape: "🤜🤛 (Dalgalanan G)",
    sampleKeywords: ["Ağaç", "Yağmur", "Dağ"],
  },
  {
    id: "tid_h",
    letter: "H",
    name: "H Harfi",
    language: "TID",
    category: "alphabet",
    description: "İki elin işaret parmakları dik tutulur, sağ elin başparmağı araya yatay köprü gibi uzanır.",
    visualTip: "İki dik direk ve ortasında yatay köprü.",
    handsRequired: 2,
    handShape: "☝️ - ☝️ (H harfi köprüsü)",
    sampleKeywords: ["Hayat", "Haber", "Hızlı"],
  },
  {
    id: "tid_i_dotless",
    letter: "I",
    name: "I Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin serçe parmağı veya işaret parmağı tek başına dik yukarı tutulur.",
    visualTip: "Tek dik parmak (noktasız).",
    handsRequired: 1,
    handShape: "☝️ (Düz dik çizgi)",
    sampleKeywords: ["Işık", "Irmak", "Ispanak"],
  },
  {
    id: "tid_i_dotted",
    letter: "İ",
    name: "İ Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ işaret parmağı dik tutulur, sol elin işaret parmağı tepesine nokta dokundurur.",
    visualTip: "Dik parmağın tepesine diğer elle nokta konur.",
    handsRequired: 2,
    handShape: "☝️ + nokta",
    sampleKeywords: ["İyi", "İnsan", "İş"],
  },
  {
    id: "tid_j",
    letter: "J",
    name: "J Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ işaret parmağıyla havada 'J' kancası çizilir.",
    visualTip: "Havada kavisli J kancası hareketi.",
    handsRequired: 1,
    handShape: "☝️ (J kavis hareketi)",
    sampleKeywords: ["Jandarma", "Jilet"],
  },
  {
    id: "tid_k",
    letter: "K",
    name: "K Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sol işaret parmağı dik tutulur; sağ elin işaret ve orta parmağı 'V' yaparak sola yanaşır.",
    visualTip: "Sol dik çizgi, sağ 'V' harfiyle birleşir.",
    handsRequired: 2,
    handShape: "I + V = K",
    sampleKeywords: ["Kitap", "Kalp", "Kardeş"],
  },
  {
    id: "tid_l",
    letter: "L",
    name: "L Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin işaret parmağı dik, başparmağı yatay açılarak 'L' şekli yapılır.",
    visualTip: "Tek elle net 90 derece L harfi.",
    handsRequired: 1,
    handShape: "👆 (90 derece L)",
    sampleKeywords: ["Lütfen", "Limon", "Lamba"],
  },
  {
    id: "tid_m",
    letter: "M",
    name: "M Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin işaret, orta ve yüzük parmakları aşağı doğru 'M' bacakları gibi bükülür.",
    visualTip: "3 parmak aşağı sarkıtılarak 'M' yapılır.",
    handsRequired: 1,
    handShape: "👇 (Aşağı bakan 3 parmak)",
    sampleKeywords: ["Merhaba", "Mutlu", "Masa"],
  },
  {
    id: "tid_n",
    letter: "N",
    name: "N Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin işaret ve orta parmağı aşağı doğru 'N' bacakları gibi bükülür.",
    visualTip: "2 parmak aşağı sarkıtılarak 'N' yapılır.",
    handsRequired: 1,
    handShape: "👇 (Aşağı bakan 2 parmak)",
    sampleKeywords: ["Nasıl", "Neden", "Nehir"],
  },
  {
    id: "tid_o",
    letter: "O",
    name: "O Harfi",
    language: "TID",
    category: "alphabet",
    description: "Tüm parmak uçları başparmakla birleştirilerek yuvarlak 'O' harfi yapılır.",
    visualTip: "Elin parmaklarıyla tam yuvarlak O.",
    handsRequired: 1,
    handShape: "👌 (Tam yuvarlak halka)",
    sampleKeywords: ["Okul", "Oyun", "Oda"],
  },
  {
    id: "tid_o_umlaut",
    letter: "Ö",
    name: "Ö Harfi",
    language: "TID",
    category: "alphabet",
    description: "'O' harfi yapıldıktan sonra diğer elin iki parmağıyla üstüne iki nokta konur.",
    visualTip: "O harfinin üstüne çift nokta dokundurulur.",
    handsRequired: 2,
    handShape: "👌 + çift nokta",
    sampleKeywords: ["Öğretmen", "Öğrenci", "Önemli"],
  },
  {
    id: "tid_p",
    letter: "P",
    name: "P Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sol işaret parmağı dik tutulur; sağ elin baş ve işaret parmağı üstte küçük halka yapar.",
    visualTip: "Sol dik çubuk, sağ üstte halka oluşturur.",
    handsRequired: 2,
    handShape: "I + üst halka = P",
    sampleKeywords: ["Para", "Pencere", "Pazar"],
  },
  {
    id: "tid_r",
    letter: "R",
    name: "R Harfi",
    language: "TID",
    category: "alphabet",
    description: "İşaret ve orta parmak birbirine dolanır (çaprazlanır).",
    visualTip: "İki parmak çapraz bağlanır.",
    handsRequired: 1,
    handShape: "🤞 (Çapraz parmaklar)",
    sampleKeywords: ["Renk", "Resim", "Rüya"],
  },
  {
    id: "tid_s",
    letter: "S",
    name: "S Harfi",
    language: "TID",
    category: "alphabet",
    description: "İki elin serçe parmakları birbirine kilitlenir (kanca gibi takılır).",
    visualTip: "İki serçe parmak kilitlenerek S oluşturur.",
    handsRequired: 2,
    handShape: "🤙 + 🤙 (Kenetlenen serçe parmaklar)",
    sampleKeywords: ["Sevgi", "Su", "Sabah"],
  },
  {
    id: "tid_s_cedilla",
    letter: "Ş",
    name: "Ş Harfi",
    language: "TID",
    category: "alphabet",
    description: "'S' harfi kenetlenmesinden sonra eller hafifçe aşağı doğru silkelenir.",
    visualTip: "Kenetli serçe parmaklar aşağı sallanır.",
    handsRequired: 2,
    handShape: "🤙 + 🤙 (Silkelenen S)",
    sampleKeywords: ["Şehir", "Şeker", "Şans"],
  },
  {
    id: "tid_t",
    letter: "T",
    name: "T Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sol işaret parmağı dik durur; sağ işaret parmağı yatay olarak tepesine değer (T şekli).",
    visualTip: "İki işaret parmağı 'T' harfi oluşturur.",
    handsRequired: 2,
    handShape: "— Üstte yatay, altta dikey",
    sampleKeywords: ["Teşekkür", "Türkiye", "Tamam"],
  },
  {
    id: "tid_u",
    letter: "U",
    name: "U Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin işaret ve başparmağı yukarı bakan 'U' çanağı oluşturur.",
    visualTip: "Yukarı açık U çanağı.",
    handsRequired: 1,
    handShape: "🤟 (U çanağı)",
    sampleKeywords: ["Umut", "Uçak", "Uzak"],
  },
  {
    id: "tid_u_umlaut",
    letter: "Ü",
    name: "Ü Harfi",
    language: "TID",
    category: "alphabet",
    description: "'U' harfi yapıldıktan sonra diğer elin iki parmağıyla üstüne iki nokta konur.",
    visualTip: "U çanağının üstüne çift nokta konur.",
    handsRequired: 2,
    handShape: "🤟 + çift nokta",
    sampleKeywords: ["Ülke", "Üniversite", "Üzüm"],
  },
  {
    id: "tid_v",
    letter: "V",
    name: "V Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin işaret ve orta parmağı açık 'V' harfi (zafer işareti) yapar.",
    visualTip: "Klasik V zafer işareti.",
    handsRequired: 1,
    handShape: "✌️ (Açık V harfi)",
    sampleKeywords: ["Vatan", "Vakit", "Ver"],
  },
  {
    id: "tid_y",
    letter: "Y",
    name: "Y Harfi",
    language: "TID",
    category: "alphabet",
    description: "Sağ elin baş ve serçe parmağı açık, ortadaki 3 parmak kapalı tutulur.",
    visualTip: "Baş ve serçe parmak açık (Y şekli).",
    handsRequired: 1,
    handShape: "🤙 (Y harfi)",
    sampleKeywords: ["Yardım", "Yarın", "Yol"],
  },
  {
    id: "tid_z",
    letter: "Z",
    name: "Z Harfi",
    language: "TID",
    category: "alphabet",
    description: "İki elin işaret parmakları birbirine paralel yatay tutulur ve havada 'Z' çizilir.",
    visualTip: "İki işaret parmağıyla Z çizimi.",
    handsRequired: 2,
    handShape: "👉 (Z kavis hareketi)",
    sampleKeywords: ["Zaman", "Zor", "Zil"],
  },
];

export const COMMON_PHRASES: SignItem[] = [
  {
    id: "common_hello",
    letter: "👋",
    name: "Hello / Merhaba",
    language: "ASL",
    category: "common",
    description: "Open hand salutes from temple outward with palm facing out.",
    turkishDescription: "Açık el şakaktan öne doğru selam verir gibi uzatılır.",
    visualTip: "Friendly salute from forehead outward.",
    handsRequired: 1,
    handShape: "✋ (Salute wave)",
    sampleKeywords: ["Hello", "Hi", "Greetings", "Merhaba", "Selam"],
  },
  {
    id: "common_thanks",
    letter: "🙏",
    name: "Thank You / Teşekkürler",
    language: "ASL",
    category: "common",
    description: "Fingertips touch the chin or lips then move forward toward the person.",
    turkishDescription: "Parmak uçları çeneye dokundurulup nazikçe öne uzatılır.",
    visualTip: "Touch chin and extend hand forward.",
    handsRequired: 1,
    handShape: "✋ (Chin forward gesture)",
    sampleKeywords: ["Thank you", "Thanks", "Teşekkürler", "Sağol"],
  },
  {
    id: "common_yes",
    letter: "👍",
    name: "Yes / Evet",
    language: "ASL",
    category: "common",
    description: "Closed fist with thumb up nods up and down like a head nodding.",
    turkishDescription: "Başparmak yukarıda yumruk kafa sallar gibi hafifçe eğilip kalkar.",
    visualTip: "Fist nodding up and down.",
    handsRequired: 1,
    handShape: "✊ (Nodding fist)",
    sampleKeywords: ["Yes", "Sure", "Evet", "Olur"],
  },
  {
    id: "common_no",
    letter: "👎",
    name: "No / Hayır",
    language: "ASL",
    category: "common",
    description: "Index and middle finger snap down onto the thumb repeatedly.",
    turkishDescription: "İşaret ve orta parmak başparmağın üstüne kapanarak hayır belirtir.",
    visualTip: "Two fingers snapping shut on thumb.",
    handsRequired: 1,
    handShape: "🤏 (Snap closed)",
    sampleKeywords: ["No", "Never", "Hayır", "Yok"],
  },
  {
    id: "common_love",
    letter: "🤟",
    name: "I Love You / Seni Seviyorum",
    language: "ASL",
    category: "common",
    description: "Thumb, index finger, and pinky finger extended simultaneously.",
    turkishDescription: "Başparmak, işaret ve serçe parmak aynı anda açık tutulur.",
    visualTip: "ASL universal ILY sign (I + L + Y).",
    handsRequired: 1,
    handShape: "🤟 (I-L-Y combined)",
    sampleKeywords: ["Love", "I love you", "Sevgi", "Seni seviyorum"],
  },
  {
    id: "common_help",
    letter: "🤝",
    name: "Help / Yardım",
    language: "ASL",
    category: "common",
    description: "Closed fist with thumb up placed on the flat palm of the other hand and lifted.",
    turkishDescription: "Başparmak yukarıda yumruk diğer elin avucuna konup yukarı kaldırılır.",
    visualTip: "Fist supported on flat palm lifting up.",
    handsRequired: 2,
    handShape: "👍 over ✋",
    sampleKeywords: ["Help", "Support", "Yardım", "Destek"],
  },
];

/**
 * Returns all signs for a given language and optional category filter
 */
export function getSigns(language: SignLanguage, category?: SignCategory): SignItem[] {
  const base = language === "ASL" ? ASL_ALPHABET : TID_ALPHABET;
  if (!category) return base;
  return base.filter((s) => s.category === category);
}

/**
 * Search signs by letter or keyword in English & Turkish
 */
export function searchSigns(language: SignLanguage, query: string): SignItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return getSigns(language);

  const pool = [...getSigns(language), ...COMMON_PHRASES];
  return pool.filter(
    (item) =>
      item.letter.toLowerCase().includes(q) ||
      item.name.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      (item.turkishDescription && item.turkishDescription.toLowerCase().includes(q)) ||
      item.sampleKeywords.some((k) => k.toLowerCase().includes(q))
  );
}
